brawlers: [ SHELLY, NITA, COLT, BULL, BROCK, EL PRIMO, BARLEY, POCO, ROSA, JESSIE, DYNAMIKE, TICK, 8-BIT, RICO, DARRYL, PENNY, CARL, JACKY, GUS, BO, EMZ, STU, PIPER, PAM, FRANK, BIBI, BEA, NANI, EDGAR, GRIFF, GROM, BONNIE, GALE, COLETTE, BELLE, ASH, LOLA, SAM, MANDY, MAISIE, HANK, PEARL, LARRY & LAWRIE, ANGELO, BERRY, SHADE, MEEPLE, MORTIS, TARA, GENE, MAX, MR.P, SPROUT, BYRON, SQUEAK, LOU, RUFFS, BUZZ, FANG, EVE, JANET, OTIS, BUSTER, GRAY, R-T, WILLOW, DOUG, CHUCK, CHARLIE, MICO, MELODIE, LILY, CLANCY, MOE, JUJU, OLLIE, SPIKE, CROW, LEON, SANDY, AMBER, MEG, SURGE, CHESTER, CORDELIUS, KIT, DRACO, KENJI ]
modes: [ MYSTERY MODE, DUELS, BRAWL BALL, GEM GRAB, BOUNTY, KNOCKOUT, KNOCKOUT 5V5, WIPEOUT, TAKEDOWN, SHOWDOWN ]
seasonal_modes: [ ROBO RUMBLE ]

position_character: [0.5, 0.5]
character_scroll_position: [0.05, 0.5]
select_character: [0.1, 0.9]
play: [0.9, 0.9]